### ISSUE TITLE
Working on Linux?

### ISSUE THREAD

**Issue by kobi86** [RazorSPoint/azuredevops-pnp-tasks#8]
Hi 

Is this add-on works on Hosted agents of type linux ?

**Comment by SebastianSchuetze** [comment]
hey @kobi86 thanks for your question. I have not tried it, but the dependency lies more with the PnP PowerShell module: https://github.com/SharePoint/PnP-PowerShell
I think they have nothing yet for PS core. Until then it would not work on a Linux agent.
